server.host: 0.0.0.0
server.ssl.enabled: true

server.ssl.key: /usr/share/kibana/config/certs/kibana.key.pem 
server.ssl.certificate: /usr/share/kibana/config/certs/kibana.crt.pem

elasticsearch.hosts: ["https://elasticsearch:9200"] # https, not http
elasticsearch.username: rafael
elasticsearch.password: rafael # the password for user kibana
elasticsearch.ssl.verificationMode: none
vega.enableExternalUrls: true
