version: '3.3'

services: 
    # Constroi o container com o Mongo DB
    mongodb:
      build:
        context: .
        dockerfile: mongodb/Dockerfile
      container_name: mongodb
      deploy:
          resources:
            limits:
              memory: 1073M
              cpus: '1'
      restart: always
      volumes:
          - type: volume
            source: mongodb
            target: /data/db
      ports: 
          - "27017:27017" 
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password

            
    # Constroi o container com o Elasticsearch
    elasticsearch:
      build:
          context: .
          dockerfile: elasticsearch/Dockerfile
      container_name: elasticsearch
      deploy:
          resources:
            limits:
              memory: 2147M
              cpus: '1'
      volumes:
          - ./shared:/usr/share/elasticsearch/shared/
          - type: bind
            source: ./elasticsearch/config/elasticsearch.yml
            target: /usr/share/elasticsearch/config/elasticsearch.yml
          - type: volume
            source: elasticsearch
            target: /usr/share/elasticsearch/data
      ports: 
          - "9200:9200"
          - "9300:9300"
      environment:
          ES_JAVA_OPTS: "-Xmx1g -Xms1g"
          ELASTIC_PASSWORD: password
          discovery.type: single-node
      configs:
          - source: elastic_config
            target: /usr/share/elasticsearch/config/elasticsearch.yml
      depends_on:
          - mongodb
    
    # Constroi o container com o Kibana
    kibana:
      build:
        context: .
        dockerfile: kibana/Dockerfile
      container_name: kibana
      deploy:
          resources:
            limits:
              memory: 1073M
              cpus: '0.5'
      volumes:
          - ./shared:/usr/share/kibana/tmp
          - type: bind
            source: ./kibana/config/kibana.yml
            target: /usr/share/kibana/config/kibana.yml
      ports: 
          - "5601:5601"
      configs:
          - source: kibana_config
            target: /usr/share/kibana/config/kibana.yml
      depends_on:
          - elasticsearch

configs:
  elastic_config:
      file: ./elasticsearch/config/elasticsearch.yml
  kibana_config:
      file: ./kibana/config/kibana.yml

volumes: 
  mongodb:
  elasticsearch:
