version: '3.3'

services: 
    #Constroi o container com o Mongo DB
    mongodb:
      build:
        context: .
        dockerfile: mongodb/Dockerfile
      container_name: mongodb
      restart: always
      ports:
        - 27017:27017
        - 9600:9600
        - 5000:5000
        - 5002:5002
        - 5004:5004
        - 5044:5044
        - 5006:5006
        - 4560:4560
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: admin
      volumes: 
        - ./mongodb/certs/:/certs/
        - ./mongodb/config/mongod.conf:/etc/mongod.conf
        - ./logstash/pipeline/:/etc/logstash/conf.d/
        - ./logstash/config/logstash.yml:/etc/logstash/logstash.yml
        - ./logstash/config/pipelines.yml:/etc/logstash/pipelines.yml
        - ./logstash/certs/:/etc/logstash/certs/
      command: ["-f", "/etc/mongod.conf"]


    # Constroi o container com o Elasticsearch
    elasticsearch:
      build:
          context: .
          dockerfile: elasticsearch/Dockerfile
      container_name: elasticsearch
      volumes:
          - ./shared:/usr/share/elasticsearch/shared/
          - ./elasticsearch/certs:/usr/share/elasticsearch/config/certs
          - type: bind
            source: ./elasticsearch/config/elasticsearch.yml
            target: /usr/share/elasticsearch/config/elasticsearch.yml
          - type: volume
            source: elasticsearch
            target: /usr/share/elasticsearch/data
      ports: 
          - "9200:9200"
          - "9300:9300"
      environment:
          ES_JAVA_OPTS: "-Xmx256m -Xms256m"
          ELASTIC_PASSWORD: password
      configs:
          - source: elastic_config
            target: /usr/share/elasticsearch/config/elasticsearch.yml
      depends_on:
          - mongodb
    
    # Constroi o container com o Kibana
    kibana:
      build:
        context: .
        dockerfile: kibana/Dockerfile
      container_name: kibana
      volumes:
          - ./kibana/certs:/usr/share/kibana/config/certs
          - ./shared:/usr/share/kibana/shared/
          - type: bind
            source: ./kibana/config/kibana.yml
            target: /usr/share/kibana/config/kibana.yml
            read_only : true
      ports: 
          - "5601:5601"
      configs:
          - source: kibana_config
            target: /usr/share/kibana/config/kibana.yml
      depends_on:
          - elasticsearch
        
configs:
    elastic_config:
        file: ./elasticsearch/config/elasticsearch.yml
    kibana_config:
        file: ./kibana/config/kibana.yml

volumes: 
  elasticsearch: