version: '3'

services: 
    # Constroi o container com o Mongo DB
    mongodb:
        image: mongo:4.2.1
        container_name: mongodb
        restart: always
        #volumes:
        #    - type: volume
        #        source: mongoDB
        #        target: /data/db
        ports: 
            - "27017:27017" 
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
    
    # Constroi o container com o Elasticsearch
    elasticsearch:
        image: elasticsearch:7.4.1
        container_name: elasticsearch
        #volumes:
        #    - type: bind
        #      source: ./elasticsearch/config/elasticsearch.yml
        #      target: /usr/share/elasticsearch/config/elasticsearch.yml
        #      read_only: true
        #    - type: volume
        #      source: elasticsearch
        #      target: /usr/share/elasticsearch/data
        ports: 
            - "9200:9200"
            - "9300:9300"
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            ELASTIC_PASSWORD: changeme
            discovery.type: single-node
        depends_on:
            - mongodb
    
    # Constroi o container com o Kibana
    kibana:
        image: kibana:7.4.1
        container_name: kibana
        #volumes:
        #    - kibana:/usr/share/kibana/config
        ports: 
            - "5601:5601"
        depends_on:
            - elasticsearch

    # Constroi o container com o Logstash
    logstash:
        image: logstash:7.4.1
        container_name: logstash
        #volumes:
        #    - kibana:/usr/share/kibana/config
        ports: 
            - "5000:5000/tcp"
            - "5000:5000/udp"
            - "9600:9600"
        depends_on:
            - elasticsearch
        volumes:
            - type: bind
                source: ./logstash/config/logstash.yml
                target: /usr/share/logstash/config/logstash.yml
                read_only: true
            - type: bind
                source: ./logstash/pipeline
                target: /usr/share/logstash/pipeline
                read_only: true

