FROM logstash:7.4.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
RUN logstash-plugin install logstash-filter-json
RUN logstash-plugin install logstash-input-file
RUN logstash-plugin install logstash-output-file
